

# This file was *autogenerated* from the file main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1)#Ploting a circle

c = circle((_sage_const_0 ,_sage_const_0 ), _sage_const_1 , rgbcolor=(_sage_const_0 ,_sage_const_1 ,_sage_const_0 ))
c.save('circle.png')

print("test")

