

# This file was *autogenerated* from the file hookejeeves.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_10 = Integer(10); _sage_const_1p0 = RealNumber('1.0'); _sage_const_2p0 = RealNumber('2.0'); _sage_const_1en6 = RealNumber('1e-6')
f = lambda x: (x[_sage_const_0 ] + x[_sage_const_1 ])**_sage_const_2  + sin(x[_sage_const_0 ] + _sage_const_2 )**_sage_const_2  + x[_sage_const_1 ]**_sage_const_2  + _sage_const_10 

def hooke_jeeves(f, x0, lam, xi, alpha):
    k = _sage_const_0 
    xk = vector(RDF, x0)
    y0 = xk
    n = len(xk)

    while lam > xi:
        y = y0
        for i in range(n):
            ei = vector(RDF, n)
            ei[i] = _sage_const_1p0 
            if f(y + lam * ei) < f(y):
                y = y + lam * ei
            elif f(y - lam * ei) < f(y):
                y = y - lam * ei
        if f(y) < f(xk):
            xk_new = y
            y0 = xk_new + alpha * (xk_new - xk)
        else:
            lam = lam / _sage_const_2p0 
            xk_new = xk
            y0 = xk
        xk = xk_new
        k += _sage_const_1 
    return xk

print(hooke_jeeves(f, vector(RDF, [_sage_const_0 , _sage_const_0 ]), lam=_sage_const_1p0 , xi=_sage_const_1en6 , alpha=_sage_const_1en6 ))


