

# This file was *autogenerated* from the file main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_5 = Integer(5); _sage_const_0 = Integer(0); _sage_const_1en5 = RealNumber('1e-5'); _sage_const_1en8 = RealNumber('1e-8'); _sage_const_10e3 = RealNumber('10e3')
def f(x,y):
    return x**_sage_const_2 +_sage_const_5 *y**_sage_const_2 
    #return (x-3)^2+(y+1)^2

def pattern_search(x=_sage_const_0 ,y=_sage_const_0 ):
    h = _sage_const_1en5 ; i = _sage_const_1en8 ; r = _sage_const_0 ; tol = _sage_const_10e3 
    #search on x1
    while f(x-h,y) < f(x,y):
        x -= h; h -= h;
        if r > tol: 
            print("Iteration limit reached.")
            break
    while f(x+h,y) < f(x,y):
        x += h; h += h
        if r > tol: 
            print("Iteration limit reached.")
            break  
    #search on x2
    while f(x,y-h) < f(x,y):
        y -= h; h -= h
        if r > tol: 
            print("Iteration limit reached.")
            break
    """
    while f(x,y+h) < f(x,y):
        y += h; h += h
        if r > tol: 
            print("Iteration limit reached.")
            break
    """
    return vector(RR,[x,y,f(x,y)])

x = RR(input("Enter x value: "))
y = RR(input("Enter y value: "))
print("Approximated Minimum: ",pattern_search(x,y))           

