

# This file was *autogenerated* from the file main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_40 = Integer(40); _sage_const_0p1 = RealNumber('0.1'); _sage_const_0p05 = RealNumber('0.05'); _sage_const_450 = Integer(450); _sage_const_1200 = Integer(1200)# Exemple 1

# Variables: x1 = dog food; x2 = cat food
print("Exemple 1")
x1 = x2 = _sage_const_0 
print("Dog food x1 = ",x1,"\nCat food x2 = ",x2)

# Objective function: f(x1,x2) = 40*x1 + 40*x2
__tmp__=var("x1,x2"); f = symbolic_expression(_sage_const_40 *x1 + _sage_const_40 *x2).function(x1,x2)
print("Objective function: f(x) =  ",f(x1,x2))

# Restrictions: 3*x1+2*x2 <= 1200; x1+2*x2 <= 800; x1 <= 300; x1, x2 >= 0

# Exercise 1

maximized = ['call minutes per month','amount of data per mounth','phone storage amount']
minimized = ['plan cost per month','phone cost','energy consumption']
cannotOptmize = ['disponible brands and models','have 4G signal']
print("Exercise 1")
print("\nMaximized: ")
for i in range (_sage_const_0 ,len(maximized)):
    print(maximized[i])

print("\nMinimized:")
for i in range (_sage_const_0 ,len(minimized)):
    print(minimized[i])

print("\nCannot optimize:")
for i in range (_sage_const_0 ,len(cannotOptmize)):
    print(cannotOptmize[i])

# Exercise 4

# Variables: a = option A; b = option B
a = _sage_const_0 
b = _sage_const_0 

# Objective function: f(a, b) = 0.1*a + 0.05*b
__tmp__=var("a,b"); f = symbolic_expression(_sage_const_0p1 *a + _sage_const_0p05 *b).function(a,b)

# Restrictions: a+b=1000000000; a <= 3b; a, b >= 0
c = a + b

""" Solution: As a linear function we can use a system of 2 variables

       	      - Objective function: f(a,b) = 0.1*a + 0.05*b
	      - Restrictions: a + b = 1000000000; a, b >= 0; a <= 3b
	
	      - Isolating a:
	      a = 1000000000 - b

	      - Replacing a on Objective function:
	      f(a.b) = 0.1*(100000000-b) + 0.05*b
	      f(a,b) = 10000000 - 0.1*b + 0.05*b
	      f(a.b) = 10000000 - 0.5b

	      - Replacing a on restriction a <= 3b
	      1000000000 - b <= 3b
	      1000000000 <= 4b
	      b >= 25000002

	      - Now, we want to minimize b because its signal is negative, so, the smaller b in range [25000000, 100000000] = 25000000
	      b = 25000000
	      a = 100000000 - 25000000 = 75000000
"""

# ---

# Exercise 5

# Variables: x = bean; y = rice
x = _sage_const_0 
y = _sage_const_0 

# Objective function: f(x,y) = 450*x + 1200*y
__tmp__=var("x,y"); f = symbolic_expression(_sage_const_450 *x + _sage_const_1200 *y).function(x,y)

# Restrictions: 30*x + 120*y <= 2400; 24*x + 60*y <= 1380; x + y <= 40; y <= 20; x, y >= 0


""" Solution:
	Objective function: P = 450*x+1200*y
	Restrictions:
		30*x+120*y=2400
		24*x+60*y=1380
		y <= 20
		x , y >= 0
		
	- Equations System:
	(I) 30*x+120*y=2400 (/2)
	(II) 24*x+60*y=1380
	
	(I) 15*x+60*y=1200 
	(II) 24*x+60*y=1380
	(II) - (I) = 19*x = 180 -> x = 9.473684211

	- Replacing x on (I)
	30*9.473684211+120*y=2400 -> y = 17.631578947
	
	- The maximum profit is:
	f(x,y)=450*x+1200*y 
	f(9.473684211,17.631578947)=450*9.473684211+1200*17.631578947=4263.15789495+21157.8947367=25421.05263165

	- Max profit: 25421.05263165

"""


