

# This file was *autogenerated* from the file main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_10 = Integer(10); _sage_const_2 = Integer(2); _sage_const_5 = Integer(5); _sage_const_1en4 = RealNumber('1e-4'); _sage_const_10e3 = RealNumber('10e3')
def func(x):
    return x**_sage_const_3 -_sage_const_10 *x**_sage_const_2 +_sage_const_5 

def tree_points_method(x,h=_sage_const_1en4 ,n=_sage_const_10e3 ):
    x1 = x - h; x2 = x + h
    while i < n:
        if func(x1) < func(x) and func(x2) < func(x):
            res vector(RR,[x,func(x)])
        elif func(x1) < func(x) and func(x2) > func(x):
            x += h
        else:
            x -= h
            
    return res

a = RR(input("Enter x value of point: "))
h = RR(input("Enter increment value: "))
n = input("Enter max iterations value")

print("Tree points method: ",tree_points_method(a,h,n))

