""" Exercise 1

(a) 3, 4
(b) 5, -2, 8
(c) 6.1, 2.7, 0, 1.2, -4.9, 12.2

As a point, a column matrix and as a line matrix

"""


# This file was *autogenerated* from the file main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_4 = Integer(4)# (a) 3, 4
a = vector(QQ, [_sage_const_3 , _sage_const_4 ])
aa = matrix([[_sage_const_3 ],[_sage_const_4 ]])
aaa = aa.transpose()

print("a = ", a)
print("A = ", aa)
print("A^t = ", aaa)

