"""
Exercise 1

(a) 3, 4
(b) 5, -2, 8
(c) 6.1, 2.7, 0, 1.2, -4.9, 12.2

As a point, a column matrix and a line matrix
"""


# This file was *autogenerated* from the file main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_2 = Integer(2); _sage_const_8 = Integer(8); _sage_const_6p1 = RealNumber('6.1'); _sage_const_2p7 = RealNumber('2.7'); _sage_const_0 = Integer(0); _sage_const_1p2 = RealNumber('1.2'); _sage_const_4p9 = RealNumber('4.9'); _sage_const_12p2 = RealNumber('12.2')
# (a) 3, 4
a = point((_sage_const_3 ,_sage_const_4 ))
aa = matrix([[_sage_const_3 ],[_sage_const_4 ]])
aaa = aa.transpose()

print("Exercise 1 \n")
print("A = ", a)
print(aa, " = A")
print("A^t = ", aaa)
print("\n")

# (b) 5, -2, 8
b = point((_sage_const_5 , -_sage_const_2 , _sage_const_8 ))
bb = matrix([[_sage_const_5 ], [-_sage_const_2 ], [_sage_const_8 ]])
bbb = bb.transpose()

print("B = ", b)
print(bb, " = B")
print("B^t = ", bbb)
print("\n")

# (c) 6.1, 2.7, 0, 1.2, -4.9, 12.2
c = point((_sage_const_6p1 , _sage_const_2p7 , _sage_const_0 , _sage_const_1p2 , -_sage_const_4p9 , _sage_const_12p2 ))
cc = matrix([[_sage_const_6p1 ], [_sage_const_2p7 ], [_sage_const_0 ], [_sage_const_1p2 ], [-_sage_const_4p9 ], [_sage_const_12p2 ]])
ccc = cc.transpose()

print("C = ", c)
print(cc, " = C")
print("C = ", ccc)
print("\n")

# ---

"""
Exercise 2
P = P0 + v*x

(a) P0 = (5,3), v = [-6,2], x = 2.5
(b) P0 = (-1,-4), v = [1,3], x = 0.1
(c) P0 = (5,0), v = [5,5], x = -2
(d) P = (4,1), P0 = (3,-6), x = 1
(e) P = (3,-2), P0 = (4,5), x = 0.4
(f) P = (5,1), P0 = (3,6), v = [4,-10]
(g) P = (-4,-2), v = [5,1], x = 2

(a) P = (5,3) + [-6,2]*2.5
    P = (5,3) + [-15,5]
    P = (-10,8)

(b) P = (-1,-4) + [1,3]*0.1
    P = (-1,-4) + [0.1,0.3]
    P = (-0.9,-3.7)

(c) P = (5.0) + [5,5]*(-2)
    P = (5,0) + [-10,-10]
    P = (-5,-10)

(d) (4,1) = (3,-6) + v*1
    v = (4,1) - (3,-6)
    v = [1,7]

(e) (3,-2) = (4,5) + v*0.4
    v = [(3,-2) - (4,5)]/0.4
    v = (-1,-7)/0.4
    v = [-2.5,-17.5]

(f) (5,1) = (3,6) + [4,-10]*x
    x = [(5,1) - (3,6)]/[4,-10]
    x = 0.5

(g) (-4,-2) = P0 + [5,1]*2
    P0 = (-4,-2) - [10,2]
    P0 = (-14,-4)
"""

# ---

print("Exercise 2\n")
print("Enter the expression: P = P0 + v*x\n")

# P
print("P = ")
a = input(); b = input()
p = vector([a, b])

# P0
print("P0 = ")
a = input(); b = input()
p0 = vector([a, b])

# V
print("v = ")
a = input(); b = input()
v = vector([a, b])

# x
print("x = ")
x = RR(input())

def unknow(p, p0, v, x):
    if p == vector(RR, [_sage_const_0 ,_sage_const_0 ]):
        res = RR(p0 + x*v)
    elif p0 == vector(RR, [_sage_const_0 ,_sage_const_0 ]):
        res = RR(p - x*v)
    elif v == vector(RR, [_sage_const_0 ,_sage_const_0 ]):
        res = RR((p - p0)/x)
    else:
        res = RR((p - p0)/x)
    return res

unknow(p, p0, v, x)

# ---

""" 
Exercise 3
Why (5,1) = (3,6) + [2,4]*x is impossible?

(5,1) = (3,6) + [2,4]*x
(5,1) - (3,6) = [2,4]*x
x = (2,-5)/[2,4]
x = (1,-1.25)

x cannot have different x and y values.
"""

# ---

"""
Exercise 4

(5,-1) = (6,-3) + [x1,x2]
(-1,2) = [x1,x2]

(-1/3,2/3) New displacement

(6,-3) + (-1/3,2/3) = (17/3,-7/3)
"""

print("Exercise 4\nNew position: (17/3,-7,3)")

