

# This file was *autogenerated* from the file main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_1en5 = RealNumber('1e-5'); _sage_const_1en8 = RealNumber('1e-8'); _sage_const_10e3 = RealNumber('10e3'); _sage_const_10 = Integer(10)
def f(x,y):
    return (x-_sage_const_3 )**_sage_const_2 +(y+_sage_const_1 )**_sage_const_2 

# Exercise 1
def pattern_search(x=_sage_const_0 ,y=_sage_const_0 ):
    h = _sage_const_1en5 ; i = _sage_const_1en8 ; r = _sage_const_0 ; tol = _sage_const_10e3 ; a = x; b = y
    while x != _sage_const_0  and y != _sage_const_0 :
        if r > tol:
            print("Iterations limit reachead.")   
        #search on x1
        while f(a - h,b) < f(a,b):
            a -= h; h -= i; i /= _sage_const_10 
        while f(a + h,b) < f(a,b):
            a += h; h += i; i /= _sage_const_10 
        #search on x2
        while f(a,b - h) < f(a,b):
            b -= h; h -= i; i /= _sage_const_10 
        while f(a,b + h) < f(a,b):
            b += h;h += i;i /= _sage_const_10 
        #search on vector direction
        while f(a + (a - x),b + (b - y)) < f(a,b):
            a += a - x;b += b - y;i /= _sage_const_10 ;
        r += _sage_const_1 
    return vector(RR,[a,b,f(a,b)])

    """
    while true:
        if f(x-h,y) < f(x,y):
            x -= h
        elif f(x+h,y) < f(x,y):
            x += h
        else:
            return vector(RR,[x,f(x,y)])
    """

#x = RR(input("Enter x value: "))
#y = RR(input("Enter y value: "))
#print("Function: f(x,y) = (x-3)^2+(y+1)^2\nApproximated Minimum: ",pattern_search(x,y))

# Plotting graphics
a, b = var('x y')
__tmp__=var("x,y"); f = symbolic_expression(x**_sage_const_2 +y**_sage_const_2 ).function(x,y)
p = plot3d(f(x,y), (x,-_sage_const_1 ,_sage_const_1 ),(y,-_sage_const_1 ,_sage_const_1 ),adaptive=True)
c = contour_plot(f(x,y),(x,-_sage_const_1 ,_sage_const_1 ),(y,-_sage_const_1 ,_sage_const_1 ),labels=True,label_colors='red')
p.save('graph.png')
c.save('contour.png')


