

# This file was *autogenerated* from the file main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_0p1 = RealNumber('0.1'); _sage_const_10e2 = RealNumber('10e2')
var('x','y')
__tmp__=var("x,y"); f = symbolic_expression((x-_sage_const_3 )**_sage_const_2 +(y+_sage_const_1 )**_sage_const_2 ).function(x,y)

def patter_search(f,x=_sage_const_0 ,y=_sage_const_0 ,h=_sage_const_0p1 ,n=_sage_const_10e2 ):
    i = _sage_const_0 
    while i < n:
        if (x+h,y) < (x,y):
            x += h
        elif (x-h,y) < (x,y):
            x -= h
        i += _sage_const_1 
    while i < n*_sage_const_2 :
        if (x,y+h) < (x,y):
            y += h
        elif (x,y-h) < (x,y):
            y -= h
        i += _sage_const_1 
    return vector(RR,[x,y])

print(patter_search(f))

