

# This file was *autogenerated* from the file main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3)
print("Exercise 1")
# Prime verification by iteration
def prime(x):
    res = 'Prime'
    for i in range(_sage_const_2 ,x):
        if x%i == _sage_const_0 :
            res = 'Not prime'
    return res

x = int(input("Enter a number to verify prime: "))
print(prime(x))

print("\nExercise 2")
# Collatz Conjecture by recursion
def collatz(x):
    if x == _sage_const_1 :
        return _sage_const_1 
    elif x%_sage_const_2  == _sage_const_0 :
        return collatz(x/_sage_const_2 )
    else:
        return collatz(_sage_const_3 *x+_sage_const_1 )

x = int(input("Enter a number to verify collatz: "))
print(collatz(x))

