

# This file was *autogenerated* from the file main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_0p1 = RealNumber('0.1'); _sage_const_2 = Integer(2)# Closed Interval Method
def closed_interval(f,a,b):
    f1 = derivative(f)
    max = min = f(a)
    while a <= b:
        if f1(a) == _sage_const_0 :
            if f(a) > max:
                max = a
            if f(a) < min:
                min = a
        a += _sage_const_0p1 
    return vector([min,f(min),max,f(max)])

__tmp__=var("x"); f = symbolic_expression(x**_sage_const_2 +_sage_const_2 *x).function(x)
a = int(input("Enter the lower limit: "))
b = int(input("Enter the upper limit: "))

print("Function: ",f,"\nMin and Max: ",closed_interval(f,a,b))

