

# This file was *autogenerated* from the file main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_10e4 = RealNumber('10e4'); _sage_const_0p0001 = RealNumber('0.0001'); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_16 = Integer(16); _sage_const_18 = Integer(18); _sage_const_2 = Integer(2)# Closed Interval Method
def closed_interval(f,a,b):
    f1 = derivative(f); max = min = a; tol = _sage_const_0 
    while a <= b or tol > _sage_const_10e4 :
        if f(a) > f(max):
            max = a
        if f(a) < f(min):
            min = a
        a += _sage_const_0p0001 ; tol += _sage_const_1 
    return vector(RR,[min,f(min),max,f(max)])

__tmp__=var("x"); f = symbolic_expression(_sage_const_3 *x**_sage_const_4 -_sage_const_16 *x**_sage_const_3 +_sage_const_18 *x**_sage_const_2 ).function(x)
a = int(input("Enter the lower limit: "))
b = int(input("Enter the upper limit: "))

print("Function: ",f,"\nMin and Max: ",closed_interval(f,a,b))

