

# This file was *autogenerated* from the file main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_10e6 = RealNumber('10e6'); _sage_const_1en1 = RealNumber('1e-1'); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_2 = Integer(2)
def f(x,y):
    return x**_sage_const_4 +y**_sage_const_4 -_sage_const_4 *x*y+_sage_const_1 

def min(x=_sage_const_0 ,y=_sage_const_0 ,tol=_sage_const_10e6 ,h=_sage_const_1en1 ):
    return vector(RR,[f(x,y),f(x+h,y),f(x-h,y),f(x,y+h),f(x,y-h)])

# Exercise 1
print("(a)\nf(3,5) =",f(_sage_const_3 ,_sage_const_5 ),"\nf(2,0) =",f(_sage_const_2 ,_sage_const_0 ),"\nf(-4,1) =",f(-_sage_const_4 ,_sage_const_1 ))
print("(b)\n",min(_sage_const_3 ,_sage_const_5 ),"\n",min(_sage_const_2 ,_sage_const_0 ),"\n",min(-_sage_const_4 ,_sage_const_1 ))

