

# This file was *autogenerated* from the file main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_0 = Integer(0)# Getting limits and tolerance
print("Enter the lower limit: ")
a = input()
print("Enter the upper limit: ")
b = input()
print("Enter the tolerance: ")
tol = input()

# Defining variable and function
var('x')
__tmp__=var("x"); f = symbolic_expression(x**_sage_const_2 +_sage_const_6 *x+_sage_const_8 ).function(x)

# Plotting functions graphic
def plotting_graphic(f, a=_sage_const_0 , b=_sage_const_0 ):
    x = var('x')
    p =  plot(f(x), (x, a, b), title='Expression', color='blue')
    p.save('expression.png')

plotting_graphic(f,a,b)



