

# This file was *autogenerated* from the file new.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_3 = Integer(3); _sage_const_15 = Integer(15); _sage_const_12 = Integer(12); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_10 = Integer(10); _sage_const_1 = Integer(1); _sage_const_1000 = Integer(1000); _sage_const_0 = Integer(0)# Function
var('x')
__tmp__=var("x"); f = symbolic_expression(x**_sage_const_2 +_sage_const_6 *x+_sage_const_8 ).function(x)
__tmp__=var("x"); f1 = symbolic_expression(x**_sage_const_3 -_sage_const_15 *x+_sage_const_12 ).function(x)
__tmp__=var("x"); f2 = symbolic_expression(x**_sage_const_4 -_sage_const_3 *x**_sage_const_3 +_sage_const_5 *x-_sage_const_10 ).function(x)
__tmp__=var("x"); f3 = symbolic_expression(exp(_sage_const_2 *x)-_sage_const_3 -_sage_const_4 *sin(x)).function(x)
__tmp__=var("x"); f4 = symbolic_expression(_sage_const_3 *x**_sage_const_2 -_sage_const_2 *sin(x)+x-exp(_sage_const_2 *x)).function(x)

# Get values
a = RR(input("Enter lower limit: "))
b = RR(input("Enter upper limit: "))
tol = RR(input("Enter tolerance: "))

# Pseudo random points
def random_point(a,b):
    while _sage_const_1 :
        x = RR.random_element(a, b)
        y = RR.random_element(a, b)
        if x!=y:
            return vector([x,y])

# Secant Method
def secant_method(f,a,b,tol):
    i = _sage_const_1000  # Max iterations
    c = _sage_const_0 
    j = _sage_const_0 
    while j<i or abs(b - a)<=tol:
        if f(x=b)-f(x=a) == _sage_const_0 :
            res = _sage_const_0 
            break
        if f(x=a) == _sage_const_0 :
            res = f(x=a)
            break
        if f(x=b) == _sage_const_0 :
            res = f(x=b)
            break
        c = b - f(x=(b))*(b-a)/(f(x=b)-f(x=a))
        a = b
        b = c
        j+=_sage_const_1 
    return vector([c, j])

v = vector(secant_method(f,a,b,tol))
print("Function: ", f, "\nApproximate root: ", v[_sage_const_0 ], "\nIterations: ", v[_sage_const_1 ], "\n")

v1 = vector(secant_method(f1,a,b,tol))
print("Function: ", f1, "\nApproximate root: ", v1[_sage_const_0 ], "\nIterations: ", v1[_sage_const_1 ], "\n")

v2 = vector(secant_method(f2,a,b,tol))
print("Function: ", f2, "\nApproximate root: ", v2[_sage_const_0 ], "\nIterations: ", v2[_sage_const_1 ], "\n")

v3 = vector(secant_method(f3,a,b,tol))
print("Function: ", f3, "\nApproximate root: ", v3[_sage_const_0 ], "\nIterations: ", v3[_sage_const_1 ], "\n")

v4 = vector(secant_method(f4,a,b,tol))
print("Function: ", f4, "\nApproximate root: ", v4[_sage_const_0 ], "\nIterations: ", v4[_sage_const_1 ], "\n")


# g = plot(f,(x,a,b),title='Function',color='#ff00ff' + point((0,v[0])))


