

# This file was *autogenerated* from the file new.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_1 = Integer(1); _sage_const_1000 = Integer(1000); _sage_const_0 = Integer(0); _sage_const_10 = Integer(10)# Function
var('x')
__tmp__=var("x"); f = symbolic_expression(x**_sage_const_2 +_sage_const_6 *x+_sage_const_8 ).function(x)

# Get values
a = RR(input("Enter lower limit: "))
b = RR(input("Enter upper limit: "))
tol = RR(input("Enter tolerance: "))

# Pseudo random points
def random_point(a,b):
    while _sage_const_1 :
        x = RR.random_element(a, b)
        y = RR.random_element(a, b)
        if x!=y:
            return vector([x,y])

# Secant Method
def secant_method(f,a,b,tol):
    i = _sage_const_1000  # Max iterations
    j = _sage_const_0 
    while j<i or abs(b - a)<=tol:
        if f(x=a) == _sage_const_0 :
            res = f(x=a)
            break
        if f(x=b) == _sage_const_0 :
            res = f(x=b)
            break
        c = b - f(x=(b))*(b-a)/(f(x=b)-f(x=a))
        a = b
        b = c
        j+=_sage_const_1 
    return res

print(secant_method(f,a,b,tol))
plot(f,(x,-_sage_const_10 ,_sage_const_10 ))

