

# This file was *autogenerated* from the file secant.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)# Function to be evalueted
var('x')
f = x**_sage_const_2 +_sage_const_6 *x+_sage_const_8 

# Get points x0, x1 and tolerance
while _sage_const_1 :
	a = RR(input("Enter x0: "))
	b = RR(input("Enter x1: "))
	if(f(x=a)*f(x=b) < _sage_const_0 ):
		break
	print("Continuous function necessary, f(x0) times f(x1) must be negative.")
tol = RR(input("Enter tolerance: "))

# Secant function
def secant_method(f,x0,x1,tol):
    fnum = f.function(x)
    i = _sage_const_0 
    while _sage_const_1 :
	i+=_sage_const_1 
	if fnum(x0) == _sage_const_0 :
	    return x0
	if fnum(x1) == _sage_const_0 :
	    return x1
	if fnum(x0) - fnum(x1) == _sage_const_0 :
	    return None
	x2 = x0 - fnum(x0)*(x1-x0)/(fnum(x1)-fnum(x0))
	x0 = x1
	x1 = x2
	if abs(x1-x0)<tol:
	    break
    print("Iterations: ", i)
    return x2

res = secant_method(f,a,b,tol)
print(res)

