

# This file was *autogenerated* from the file main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_36 = Integer(36); _sage_const_1en4 = RealNumber('1e-4'); _sage_const_1000 = Integer(1000); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)#Bisection Method
def calc_f(x):
    return _sage_const_3 *x**_sage_const_2 -_sage_const_36 

def bisection_method(a,b,tol=_sage_const_1en4 ,N=_sage_const_1000 ):
    i = _sage_const_0 ; c = (a + b)/_sage_const_2 
    while (abs(calc_f(c)) >= tol) or (i < N):
        if calc_f(a)*calc_f(c) > _sage_const_0 :
            a = c
        else:
            b = c
        c = (a + b)/_sage_const_2 
        i += _sage_const_1 
    return vector(RR,[c,calc_f(c)])

a = RR(input("Enter the lower limit: "))
b = RR(input("Enter the upper limit: "))
tol = RR(input("Enter tolerance: "))
N = RR(input("Enter iterations max: "))

print("Root on interval [",a,",",b,"] ->",bisection_method(a,b,tol,N))

#Secant Method
def secant_method(a,b,tol=_sage_const_1en4 ,N=_sage_const_1000 ):
    i = _sage_const_0 ; c = a
    while abs(b - a) < tol or i < N:
        c = b - (calc_f(b)*(b - a))/calc_f(b) - calc_f(a)
        a = b; b = c; i += _sage_const_1 
    return vector(RR,[c,calc_f(c)])

print("Secant method: ",secant_method(a,b,tol,N))

"""
Line Equation

General: ax+by+c=0
Reduced: y=ax+b

det |x  y  1 |
    |x1 y1 1 |
    |x2 y2 1 |

or

y-y0/y1-y0 = x-x0/x1-x0
"""

"""
x interception

when y=0
"""

