

# This file was *autogenerated* from the file main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_36 = Integer(36); _sage_const_0 = Integer(0); _sage_const_10 = Integer(10); _sage_const_1 = Integer(1)# Test function
var('x')
__tmp__=var("x"); f = symbolic_expression(_sage_const_3 *x**_sage_const_2 -_sage_const_36 ).function(x)

# Bisection Technique(binary-search)
def bisection_method(f,a,b):
    p = a
    tol = _sage_const_0 
    p = (a + b)/_sage_const_2 
    while (f(x=p) != _sage_const_0 ) or (tol < exp(_sage_const_10 )):
        if p*f(x=a) > _sage_const_0 :
            a = p 
        else:
            b = p
         
        p = (a + b)/_sage_const_2 
        tol = tol+_sage_const_1 
    return vector(RR,[p,f(x=p)])

a = RR(input("Enter the lower limit: "))
b = RR(input("Enter the upper limit:  "))

print("Root of function",f,"on interval [",a,",",b,"] ->",bisection_method(f,a,b))

