"""

# Defining a function
f(x) = 2*x
print("f(2) = ", f(2), "\nf(-2) = ", f(-2), "\nf(0) = ", f(0), "(root)")

m = -2
n = 1/10
a = 1
b = 2

def f(x):
    return 2*x

# Saving graphic of functions
plot(m*f(n*(x-a))+b, x, -10, 10).save('m*f(n*(x-a))+b.png')
plot(sin(x), x, -10, 10).save(./graphic/'sin(x).png')

"""


# This file was *autogenerated* from the file precalculus.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_30 = Integer(30)
p  = plot((x**_sage_const_2 -_sage_const_1 )/(x-_sage_const_1 ), x, -_sage_const_1 , _sage_const_3 )
pt  = point((_sage_const_1 ,_sage_const_2 ), rgbcolor='white', pointsize=_sage_const_30 , faceted=True)
g = p + pt
g.save('(x^2-1)/(x-1).png')

