"""
Name: Guilherme Soares Silva
Reg. Code: 2025119440
Algorithm: Ternary Search by Golden Ration section
"""


# This file was *autogenerated* from the file golden-ratio-search.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_7 = Integer(7); _sage_const_0p0001 = RealNumber('0.0001'); _sage_const_0p382 = RealNumber('0.382'); _sage_const_0p618 = RealNumber('0.618')
var('x')
__tmp__=var("x"); f = symbolic_expression(_sage_const_3 *x**_sage_const_2 +_sage_const_2 *x-_sage_const_7 ).function(x)
a = RR(input("Enter the lower limit: "))
b = RR(input("Enter the upper limit: "))

# Ternary Search Method by Golden Ration section (minimum)
def ternary_search(f,a,b):
    i = _sage_const_0p0001 
    while abs(a-b) > i:
        c = (_sage_const_2 *a-b)*_sage_const_0p382 ; d = (a-_sage_const_2 *b)*_sage_const_0p618 
        if f(x=c) > f(x=d):
            a = c
        else:
            b = d
    if a < b:
        return a, f(x=a)
    else:
        return b, f(x=b)

print("Minimum of function ",f," is ",ternary_search(f,a,b))

