"""
Name: Guilherme Soares Silva
Reg. Code: 2025119440
Algorithm: Golden Section Search
"""


# This file was *autogenerated* from the file golden-section-search.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_7 = Integer(7); _sage_const_1en4 = RealNumber('1e-4'); _sage_const_5 = Integer(5); _sage_const_1 = Integer(1)
var('x')
__tmp__=var("x"); f = symbolic_expression(_sage_const_3 *x**_sage_const_2 +_sage_const_2 *x-_sage_const_7 ).function(x)
a = RR(input("Enter the lower limit: "))
b = RR(input("Enter the upper limit: "))

# Golden Section Search (minimum)
def ternary_search(f,a,b):
    i = RR(_sage_const_1en4 )
    phi = RR((sqrt(_sage_const_5 )-_sage_const_1 )/_sage_const_2 )
    while abs(b-a) > i:
        c = b-phi*(b-a); d = a+phi*(b-a)
        if f(x=c) > f(x=d):
            a = c
        else:
            b = d
    if a < b:
        return a, f(x=a)
    else:
        return b, f(x=b)

print("Minimum of function ",f," is ",ternary_search(f,a,b))

