

# This file was *autogenerated* from the file main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_0p0001 = RealNumber('0.0001')# Get function, lower and upper delimiters
var('x')
__tmp__=var("x"); f = symbolic_expression(input("Enter the function: ")).function(x)
a = RR(input("Enter the lower limit: "))
b = RR(input("Enter the upper limit: "))

# Shubert-Piyavskii Method(aka Sawtooth Method)
#def sawtooth_method(f,a,b):

# Ternary search implemantation (minimum)
def ternary_search(f,a,b):
    c = (_sage_const_2 *a+b)/_sage_const_3 ; d = (a+_sage_const_2 *b)/_sage_const_3 ; i = _sage_const_0p0001 
    while abs(b-a) > i:
        if f(x=c) < f(x=d):
            b = d
        else:
            a = c
    return a if a < b else b

res = ternary_search(f,a,b)
print("Minimum of ",f," is ",res)

