"""
Name: Guilherme Soares Silva
Reg. Code: 2025119440
Algorithm: Ternary Search with normal section
"""


# This file was *autogenerated* from the file ternary-search.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_0p0001 = RealNumber('0.0001'); _sage_const_3 = Integer(3)
var('x')
__tmp__=var("x"); f = symbolic_expression(x**_sage_const_2 +_sage_const_2 *x ).function(x)# Test function

# Get lower and upper delimiters
a = RR(input("Enter the lower limit: "))
b = RR(input("Enter the upper limit: "))

# Ternary search implemantation (minimum)
def ternary_search(f,a,b):
    i = _sage_const_0p0001 
    while abs(b-a) > i:
        c = (_sage_const_2 *a+b)/_sage_const_3 ; d = (a+_sage_const_2 *b)/_sage_const_3 
        if f(x=c) < f(x=d):
            b = d
        else:
            a = c
    if a<b:
        return a, f(x=a)
    else:
        return b, f(x=b)

print("Minimum of ",f," is ",ternary_search(f,a,b))

