

# This file was *autogenerated* from the file main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_1en2 = RealNumber('1e-2')
def f(x,y):
    return (x-_sage_const_3 )**_sage_const_2 +(y+_sage_const_1 )**_sage_const_2 

# Exercise 1
def pattern_search(x=_sage_const_0 ,y=_sage_const_0 ):
    h = _sage_const_1en2 
    while true:
        if f(x-h,y) < f(x,y):
            x -= h
        elif f(x+h,y) < f(x,y):
            x += h
        else:
            return vector(RR,[x,f(x,y)])

x = RR(input("Enter x value: "))
y = RR(input("Enter y value: "))
print(pattern_search(x,y))

